# This file was generated by GoReleaser. DO NOT EDIT.
class Babycron < Formula
  desc "Run a single cron job in the foreground."
  homepage "https://github.com/meowgorithm/babycron"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/meowgorithm/babycron/releases/download/v1.0.1/babycron_1.0.1_macOS_x86_64.tar.gz"
    sha256 "0db5e0d5d0be23d462015315305a1fca8a05c269dc332dbccb864ef632c23dc2"
  end

  def install
    bin.install "babycron"
  end
end
