# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Babycron < Formula
  desc "Run a single cron job in the foreground."
  homepage "https://github.com/meowgorithm/babycron"
  version "1.0.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meowgorithm/babycron/releases/download/v1.0.2/babycron_1.0.2_macOS_x86_64.tar.gz"
      sha256 "9504ed994f4e25d92d6d31f26e390b0e4320138d53059867a7866e256789791d"

      def install
        bin.install "babycron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meowgorithm/babycron/releases/download/v1.0.2/babycron_1.0.2_macOS_arm64.tar.gz"
      sha256 "6ad95f2bed82c513bb8eb727b98a5ed46d2a24d71fede09f89dd953ca15a152b"

      def install
        bin.install "babycron"
      end
    end
  end
end
