# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipedream < Formula
  desc "A multipart uploader for S3 and S3-compatible services."
  homepage "https://github.com/meowgorithm/pipedream"
  version "1.1.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meowgorithm/pipedream/releases/download/v1.1.1/pipedream_1.1.1_macOS_x86_64.tar.gz"
      sha256 "21a0eb9109644504b80dc2cb5bd0be84e066bb5cb25c4a2885037ddbc896048b"

      def install
        bin.install "pipedream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meowgorithm/pipedream/releases/download/v1.1.1/pipedream_1.1.1_macOS_arm64.tar.gz"
      sha256 "11cf2965f9c722b283332d0682b9f466b989d2f68860cffcb849cf1585730b82"

      def install
        bin.install "pipedream"
      end
    end
  end
end
